### ISSUE TITLE
support separate helmfiles / directories per namespace?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-gitops#187]
so make it easier to understand what apps are in what namespace & to more easily configure namespace specific values (ingress / image pull secrets etc) we should probably move to a helmfile per namespace for staging / production / secrets-infra etc. Then each helmfile can reference its own namespace specific environment yaml for ingress domains etc

e.g. a cluster repository could have a layout like this:

```
helmfiles/
  namespaces/
    jx/
      helmfile.yaml
    jx-staging/
      helmfile.yaml
```

then its just usually 1 helmfile to look at in a specific namespace to see whats in staging or whatever.

If needed folks could add an `OWNERS` file in a particular namespace to have team specific review/approvers for different namespaces.

We could also support composite apps being deployed to a namespace by allowing a custom app helmfile to be deployed. e.g. `my-system.helmfile.yaml` could contain N charts of different versions and be deployed into `helmfiles/namespaces/jx-staging/my-system.helmfile.yaml` via `jx promote`?

**Comment by jstrachan** [comment]
a nice effect of this could be to support separate teams for each namespace and use lighthouse & `OWNERS` files in each dir

**Comment by salaboy** [comment]
100% percent.. invest in this kind of research.. this is going to make a real difference in how we promote the line between complex apps and infra
