### ISSUE TITLE
jx gitops upgrade: should verify there are no pending git commits first

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-gitops#251]
to avoid `kpt pkg update` failing later on.

we should be able to use the `gitclient.HasChanges(gitClient, dir)` function: https://github.com/jenkins-x/jx-helpers/blob/master/pkg/gitclient/helpers.go#L224 to check if there are local changes

**Comment by sladyn98** [comment]
@jstrachan I could maybe add this, where exactly is the kpt pkg update being called ?

**Comment by jstrachan** [comment]
@sladyn98 so sorry I missed your comment. We could add a check to the above HasChanges function at the start of the `jx gitops upgrade` command and fail if there are any pending changes found.

e.g. add a check here that git is clean and fail if there are local changes: https://github.com/jenkins-x/jx-gitops/blob/master/pkg/cmd/kpt/update/update.go#L110
