### ISSUE TITLE
make it easier to understand `jx-apps.yml` -> yaml

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-gitops#32]
right now there's way too much magic in the [jx gitops jx-apps template](https://github.com/jenkins-x/jx-gitops/blob/master/docs/cmd/jx-gitops_jx-apps_template.md) command around:
* templating/finding `values.yaml` / `values.yaml.gotmpl` files
* finding helm charts
* running `helm template` and copying the files into git

Folks shouldn't have to learn lots of CLI tools or magic - it'd be nice to make things more self-evident. 

e.g. we already have a simple [git repostory layout](https://github.com/jenkins-x/jx-gitops/blob/master/docs/git_layout.md).

I wonder if we should try decouple the step in this command so there's an easier to grok intermediate format?

e.g.

* template the yaml files + fetch the charts and output the results somewhere. e.g. something like...

``` 
./build/
  helm/
    charts/
      myprefix/
        mychart/
          Chart.yaml
          values.yaml
          templates/
              deployment.yaml
        ...
          # generated/copied values.yaml files to be applied
          overrides/
             values.yaml
             another-values.yaml
          # shell script which runs `helm template --values overrides/values.yaml --values/another-values.yaml releasename myprefix/mychart
          # then copies the values to a canonical place...
          helm-template.sh

     # top level script which invokes all the ./charts/myprefix/mychart/helm-template.sh scripts
     helm-template.sh
``` 

Then if someone wanted to tinker with a specific chart they could do something like...

```bash 
cd build/helm/charts/myprefix/mychart

## todo edit overrides/values.yaml by hand...

./helm-template.sh
```

everything is then self-documenting; you can see all the values files passed into the template `myprefix/mychart` by looking in the files at `build/helm/charts/myprefix/mychart/overrides/*.yaml` or looking at the command line at `build/helm/charts/myprefix/mychart/helm-template.sh`

**Comment by rawlingsj** [comment]
we use helmfile now
